#!/bin/sh


REPOS="candlepin buildr pulp"


for repo in REPOS
do
    rm -rf /tmp/$repo
    mkdir -p /tmp/$repo-repo
done

cp /home/ayoung/rpmbuild/RPMS/ruby*  /tmp/buildr-repo
cp /home/ayoung/rpmbuild/SRPMS/ruby*  /tmp/buildr-repo

mkdir -p /tmp/candlepin-repo

CANDLEPIN_SPECS="activation bcpg-jdk16 bcprov-jdk16 commons-pool emma gettext-commons guice hibernate httpclient httpcore jackson jakarta jaxb-impl jaxrs-api jettison jmock jsr311-api jta log4j mockito persistence-api quartz resteasy scannotation servlet-api stax-api stax-ex wstx xalan-j2"

#CANDLEPIN_UNUSED="aopalliance asm3 cglib freemarker "


for spec in $CANDLEPIN_SPECS
do
    echo copying: /home/ayoung/rpmbuild/RPMS/$spec*rpm
    rsync  /home/ayoung/rpmbuild/RPMS/$spec*rpm /tmp/candlepin-repo
    rsync /home/ayoung/rpmbuild/SRPMS/$spec*rpm /tmp/candlepin-repo
done

PULP_SPECS="mongo python-greenlet python-gevent pulp grinder python-pymongo"
for spec in $PULP_SPECS
do
    echo copying: /home/ayoung/rpmbuild/RPMS/$spec*rpm
    rsync  /home/ayoung/rpmbuild/RPMS/$spec*rpm /tmp/pulp-repo
    rsync /home/ayoung/rpmbuild/SRPMS/$spec*rpm /tmp/pulp-repo
done

for repo in $REPOS
do        
	pushd /tmp/$repo-repo
	createrepo $PWD
	rsync -av . admiyo@admiyo.fedorapeople.org:public_html/$repo-repo
	popd
done




